### ISSUE TITLE
Working with monaco editor

### ISSUE THREAD

**Issue by mehulmpt** [georgewfraser/java-language-server#134]
Can anybody direct me on integrating this with Monaco editor? I've started the server, but I'm unsure of how to link it. I believe Monaco only support socket-based connections whereas this server only supports io based connection.

**Comment by georgewfraser** [comment]
JLS is built into a folder, dist, that contains everything you need to run with no dependencies. You are correct that it currently only supports communicating via STDIO. The relevant code is here:

https://github.com/georgewfraser/java-language-server/blob/d9c8c8658780e5f3681d8dd3ed94d35de5cfac6f/src/main/java/org/javacs/Main.java#L30

Adding support for TCP sockets would be straightforward, and I would accept a PR adding a startup option that tells JLS to run in socket mode rather than stdio mode.

**Comment by chaitanya71998** [comment]
hi @mehulmpt can you share what steps have you done to integrate a java language server with monaco editor.
I was not clear on these concepts. It will be very helpful to many too.
Thank you
