### ISSUE TITLE
Couldn't start client Java Language Server

### ISSUE THREAD

**Issue by Hyraeth** [georgewfraser/java-language-server#92]
Hello, I have this issue since a month and I thought I could just ignore it but it would be nice to know how to solve it. I use VS Code.

Thank you.

**Comment by Yanpas** [comment]
Yep, no signs of life after I installed extension and opened java file, even no output channel.
Ubuntu 18.10

**Comment by reznikmm** [comment]
I've installed an extension in vscode, then open a java file. Vscode complains:
> Activating extension 'georgewfraser.vscode-javac' failed: undefined.

Ubuntu 18.04. Vscode: 1.33.1

**Comment by reznikmm** [comment]
It seems Linux isn't [supported at all](https://github.com/georgewfraser/java-language-server/blob/6c8b2e532a287ca48d8aaff79b894aba428f976d/lib/extension.ts#L217).

**Comment by georgewfraser** [comment]
@reznikmm It's just a matter of adding a case to the function you mentioned, and adding a linux build step to scripts/build.sh

**Comment by marmistrz** [comment]
@georgewfraser couldn't the extension just look for `java-language-server` on `PATH`?

**Comment by marmistrz** [comment]
In ny opinion it's unnecessary bloat. If user wishes to download the language server, the extension should download it later on, if the user wishes to. On Linux, I have my package manager for that.

**Comment by marmistrz** [comment]
The binaries shipped with the extensions are about 40MB for every platform. dlls for windows & dylibs for mac take up about 15MB each. I don't need 80MBs of garbage binaries on my hard drive, I don't need to download 30MB of garbage binaries just to never ever use them. On mac, even `javac` is provided by the extension!

I don't want to add another megabytes of shared libraries for Linux, because I have my distribution to provide them and provide security updates. I also have my package manager to install the language server. Look at the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=java-language-server).

And what if we decide to support *BSD in the future? arm, armv7 or aarch64 Linux? A binary for every possible combination of architecture and OS?

The way I see it:
* the extension should not ship any binaries, be as lightweight as possible
* if JLS is not available in `PATH` and the platform has prebuilt binaries, the extension proposes to download the binaries for the OS, which are downloaded **if and only if** the user agrees to

**Comment by georgewfraser** [comment]
@marmistrz I ran a quick check to see how much extra space is being used by shipping both windows and mac in the same .vsix file:

```
zip test.zip $(find dist/mac) $(find dist/windows)
du -h dist/mac > 39 M
du -h dist/windows > 40M
du -h test.zip > 54M
```

So there's an extra 15M to download, and when it's expanded after it's downloaded there's an extra 40-54M. It's possible to optimize this by [downloading the extension in two phases](https://github.com/microsoft/vscode/issues/23251#issuecomment-406090410) but I don't think it's enough space to be worth the added complexity.

Packaging java-language-server as a standalone, multi-platform vscode extension is a great solution because it provides a simple user experience and avoids the entire category of bugs that come from mismatching versions of Java. We just need to add one more binary, for linux. VSCode is only supported on mac, windows, and linux, so there will be no more platforms.

Packaging java-language-server for vim, emacs, or other editors may require different approaches, I am not an expert on those editors.

**Comment by marmistrz** [comment]
I took a quick look at the change: why are you bundling the whole JDK with the extension? I have my distribution to provide the JDK, and I need one anyway to compile stuff with gradle or maven.
